### ISSUE TITLE
Can't run appimage

### ISSUE THREAD

**Issue by duongbaoquy** [boolean-world/appimage-resources#2]
I am trying to follow the steps in [HERE](https://www.booleanworld.com/creating-linux-apps-run-anywhere-appimage/) 
but when i run command : "/path/to/appimagetool-x86_64.AppImage hello-world-appimage/"
i got the error: "Categories entry not found in desktop file
.desktop file is missing a Categories= key"
what should i do now?

**Comment by michel47** [comment]
you would need add a registered category in your helloworld.desktop file ... see [here](https://github.com/michel47/hello-world-appimage/tree/master/hello-world-appimage)
